Repository AY2425S1-CS2113-W13-2/tp, pull requests merged in 2024-11, with the labels that each got.

#171 Feat: Add unit test classes for all six ExerciseStation subclasses
  src/main/java/fittrack/calculator/SitUpCalculator.java
  src/main/java/fittrack/calculator/StandingBroadJumpCalculator.java
  src/test/java/fittrack/exercisestation/PullUpStationTest.java
  src/test/java/fittrack/exercisestation/ShuttleRunStationTest.java
  src/test/java/fittrack/exercisestation/SitAndReachStationTest.java
  src/test/java/fittrack/exercisestation/SitUpStationTest.java
  src/test/java/fittrack/exercisestation/StandingBroadJumpStationTest.java
  src/test/java/fittrack/exercisestation/WalkAndRunStationTest.java
  src/test/java/napfa/DukeTest.java
Labels: type.Task, priority.High

#173 Docs: Elaborate on High Level Functionalities
  docs/DeveloperGuide.md
  docs/Diagrams/Class_AddTrainingSession.puml
  docs/Diagrams/Class_DeleteTrainingSession.puml
  docs/Diagrams/Class_ViewTrainingSession.puml
  docs/Images/Class_AddTrainingSession.png
  docs/Images/Class_DeleteTrainingSession.png
  docs/Images/Class_ViewTrainingSession.png
  docs/UserGuide.md
  docs/team/img.png
  docs/team/zackermaxsee.md
Labels: type.Task, priority.Low

#174 Update UserGuide with Reminder Functionality
  docs/UserGuide.md
Labels: type.Task, priority.Low

#175 docs: enhance sequence diagram to include FitTrack interaction
  docs/Diagrams/Sequence_addTrainingSession.puml
  docs/Images/Sequence_addTrainingSessionCommand.png
Labels: priority.High

#180 docs: update Project Portfolio Page
  docs/team/CheeKiang.md
Labels: priority.High

#178 Update thedinos ppp.
  docs/team/marcuswong.md
  docs/team/thedinos.md
Labels: priority.Low

#193 118 feature implement visualisation tools for students to track fitness metrics
  src/main/java/fittrack/exercisestation/ExerciseStation.java
  src/main/java/fittrack/exercisestation/PullUpStation.java
  src/main/java/fittrack/exercisestation/ShuttleRunStation.java
  src/main/java/fittrack/exercisestation/SitAndReachStation.java
  src/main/java/fittrack/exercisestation/SitUpStation.java
  src/main/java/fittrack/exercisestation/StandingBroadJumpStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
  src/main/java/fittrack/graph/Graph.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.Low

#197 195 dg add graphing feature
  docs/DeveloperGuide.md
  docs/Diagrams/Sequence_graphExercisePerformance.puml
  docs/Diagrams/Sequence_graphSessions.puml
  docs/Images/Sequence_graphExercisePerformance.png
  docs/Images/Sequence_graphSessions.png
Labels: priority.Low

#196 100 implement exceptions for invalid exercisedata input
  docs/team/img.png
  src/main/java/fittrack/FitTrack.java
  src/main/java/fittrack/enums/Exercise.java
  src/main/java/fittrack/exception/ParserExceptions.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/ui/Ui.java
Labels: type.Task, priority.High

#199 Docs: Sequence diagrams for DG High Level Functionalities
  docs/DeveloperGuide.md
  docs/Diagrams/Sequence_DeleteTrainingSession.puml
  docs/Diagrams/Sequence_ListTrainingSessions.puml
  docs/Images/Sequence_DeleteTrainingSession.png
  docs/Images/Sequence_ListTrainingSessions.png
  src/main/java/fittrack/ui/Ui.java
Labels: type.Task, priority.Low

#204 Branch time-based graph
  src/main/java/fittrack/graph/Graph.java
Labels: type.Story, priority.High

#218 Docs: Update DG for High Level Functionalities
  docs/DeveloperGuide.md
  docs/Diagrams/Archi_Architecture.puml
  docs/Diagrams/Sequence_SetUser.puml
  docs/Diagrams/Sequence_ViewTrainingSession.puml
  docs/Images/Archi_Architecture.png
  docs/Images/Sequence_SetUser.png
  docs/Images/Sequence_ViewTrainingSession.png
Labels: type.Task, priority.High

#224 Docs: Update DG for High Level Functionalities
  FitTrackLogger.log
  data/saveFile.txt
  docs/DeveloperGuide.md
  docs/Diagrams/Archi_Architecture.puml
  docs/Images/Archi_Architecture.png
  src/main/java/fittrack/parser/Parser.java
Labels: type.Task, priority.High

#225 Docs: Update UG with final V2.0 functionality
  FitTrackLogger.log
  data/saveFile.txt
  docs/UserGuide.md
  src/main/java/fittrack/FitTrack.java
  src/main/java/fittrack/exception/ParserExceptions.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
Labels: type.Task, priority.High

#216 Integrate Mood with TraininSession class & Make user infomation persistant on a session-by-session basis
  .gitignore
  FitTrackLogger.log
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/main/java/fittrack/ui/Ui.java
  src/main/java/fittrack/user/User.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
  src/test/java/fittrack/ui/UiTest.java
Labels: type.Task, priority.High

#227 205 docs update dg for high level functionalities
  FitTrackLogger.log
  docs/Calculator.puml
  docs/DeveloperGuide.md
  docs/Diagrams/Class_GraphOverview.puml
  docs/Diagrams/getPointsSequenceDiagram.puml
  docs/Images/getPointsSequenceDiagram.png
  docs/LowLevel.puml
  docs/TrainingSessionClassDiagram.puml
  docs/viewSessionSequenceDiagram.puml
Labels: priority.Low

#228 205 docs update dg for v20
  docs/DeveloperGuide.md
  docs/Diagrams/Class_Overall.puml
  docs/Images/Class_Overall.png
Labels: type.Task, priority.High

#234 233 implement user input for graphing functionalities
  docs/DeveloperGuide.md
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/ui/Ui.java
Labels: priority.High

#235 Branch updateDGv2
  docs/DeveloperGuide.md
  docs/Diagrams/Sequence_graphPerformanceTime.puml
  docs/Images/Sequence_graphPerformanceTime.png
  src/main/java/fittrack/graph/GraphPerformance.java
  src/main/java/fittrack/graph/GraphPerformanceTime.java
Labels: priority.High

#237 Branch update ug
  docs/UserGuide.md
Labels: priority.High

#246 UG Help Function Typo Fix
  docs/UserGuide.md
Labels: type.Task, priority.Low

#309 Parser now accepts lowercase exercise acronyms
  META-INF/MANIFEST.MF
  data/saveFile.txt
  src/main/java/fittrack/FitTrack.java
  src/main/java/fittrack/exception/ParserExceptions.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/ui/Ui.java
Labels: type.Bug, priority.High

#310 Explicitly list exercise acronyms in userguide and help function
  data/saveFile.txt
  docs/DeveloperGuide.md
  docs/Diagrams/Sequence_DeleteTrainingSession.puml
  docs/Diagrams/Sequence_ListTrainingSessions.puml
  docs/Diagrams/Sequence_SetUser.puml
  docs/Diagrams/Sequence_ViewTrainingSession.puml
  docs/Diagrams/Sequence_editExercise.puml
  docs/Images/Class_Overall.svg
  docs/Images/Sequence_DeleteTrainingSession.png
  docs/Images/Sequence_GraphPerformanceRepsDistance.png
  docs/Images/Sequence_ListTrainingSessions.png
  docs/Images/Sequence_SetUser.png
  docs/Images/Sequence_ViewTrainingSession.png
  docs/Images/Sequence_editExercise.png
  docs/Images/Sequence_graphSessions.png
  docs/UserGuide.md
  src/main/java/fittrack/messages/Messages.java
Labels: type.Bug, priority.High

#312 307 pe dtester c add session function does not allow for datetime input or editing
  docs/DeveloperGuide.md
  docs/Diagrams/Sequence_ModifyTrainingSession.puml
  docs/Images/Sequence_ModifyTrainingSession.png
  docs/UserGuide.md
  docs/team/zackermax.md
  docs/team/zackermaxsee.md
  src/main/java/fittrack/exception/ParserExceptions.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/main/java/fittrack/ui/Ui.java
Labels: type.Bug, priority.High

#319 Add missing commands gpoints and gperformance to help command.
  docs/UserGuide.md
  src/main/java/fittrack/messages/Messages.java
Labels: priority.Low

#325 Update modify command logic.
  docs/UserGuide.md
  src/main/java/fittrack/exception/ParserExceptions.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/test/java/fittrack/parser/ParserTest.java
Labels: priority.High

#330 Fixed user initialisation
  data/saveFile.txt
  src/main/java/fittrack/FitTrack.java
Labels: type.Bug, priority.High

#337 New JUnit Tests for Ui
  src/main/java/fittrack/parser/Parser.java
  src/test/java/fittrack/ui/UiTest.java
Labels: type.Task, priority.High

#344 Update UG with more information about set user usage.
  docs/UserGuide.md
Labels: priority.High

#357 Add JUnit tests and Javadoc for Graph classes.
  src/main/java/fittrack/graph/GraphBase.java
  src/main/java/fittrack/graph/GraphPerformance.java
  src/main/java/fittrack/graph/GraphPerformanceRepsDistance.java
  src/main/java/fittrack/graph/GraphPoints.java
  src/test/java/fittrack/graph/GraphPerformanceRepsDistanceTest.java
  src/test/java/fittrack/graph/GraphPointsTest.java
Labels: priority.High

#360 Fix formatting for table.
  docs/UserGuide.md
  docs/team/thedinos.md
Labels: priority.High

#363 Update thedinos ppp.
  docs/team/thedinos.md
Labels: priority.High

#371 Refactor AboutUs
  docs/AboutUs.md
Labels: type.Task, priority.High
