Repository AY2425S1-CS2113-W13-2/tp, pull requests merged in 2024-10, with the labels that each got.

#65 Add invalidAge Exception
  src/main/java/fittrack/calculator/Calculator.java
  src/main/java/fittrack/exception/InvalidAgeException.java
  src/main/java/fittrack/lookupkey/LookUpKey.java
Labels: type.Task

#74 Refactor non-time calculator classes
  src/main/java/fittrack/calculator/PullUpCalculator.java
  src/main/java/fittrack/calculator/ShuttleRunCalculator.java
  src/main/java/fittrack/calculator/SitAndReachCalculator.java
  src/main/java/fittrack/calculator/SitUpCalculator.java
  src/main/java/fittrack/calculator/StandingBroadJumpCalculator.java
  src/main/java/fittrack/calculator/WalkAndRunCalculator.java
Labels: priority.High

#75 Branch recitfy training session outputs
  src/main/java/fittrack/exercisestation/PullUpStation.java
  src/main/java/fittrack/exercisestation/ShuttleRunStation.java
  src/main/java/fittrack/exercisestation/SitAndReachStation.java
  src/main/java/fittrack/exercisestation/SitUpStation.java
  src/main/java/fittrack/exercisestation/StandingBroadJumpStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/test/java/fittrack/Calculator/PullUpCalculatorTest.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#77 Rectify award calculation in TrainingSession class
  FitTrackLogger.log
  src/main/java/fittrack/trainingsession/TrainingSession.java
Labels: priority.High

#81 Feat: Add assertions in calculator and lookupkey class
  src/main/java/fittrack/calculator/Calculator.java
  src/main/java/fittrack/lookupkey/LookUpKey.java
Labels: type.Task, priority.Medium

#85 Fix: Modify Parser to accommodate changes to TrainingSession
  src/main/java/fittrack/parser/Parser.java
Labels: type.Task, priority.Medium

#88 Process rep data differently for timing exercises.
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#90 Fix: Modify Parser to accommodate changes to TrainingSession
  src/main/java/fittrack/parser/Parser.java
Labels: type.Task, priority.Medium

#91 Update sessionDatetime in TrainingSession to LocalDatetime object.
  src/main/java/fittrack/trainingsession/TrainingSession.java
Labels: priority.High

#93 Fix: Modify UiTest to accommodate changes to Ui
  src/test/java/fittrack/UiTest.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: type.Task, priority.High

#94 Update accurate WalkAndRun timings.
  src/main/java/fittrack/calculator/WalkAndRunCalculator.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#95 Implement "NA" initial value for timing related exercises.
  src/main/java/fittrack/exercisestation/ExerciseStation.java
  src/main/java/fittrack/exercisestation/ShuttleRunStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#96 Create WalkAndRunCalculatorTest.
  src/test/java/fittrack/Calculator/WalkAndRunCalculatorTest.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#98 Update formatting of toString method of exercise related classes.
  src/main/java/fittrack/exercisestation/ShuttleRunStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#102 Fix format for WalkAndRun timings.
  src/main/java/fittrack/exercisestation/ExerciseStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: priority.High

#103 Feat: Add help function
  FitTrackLogger.log
  src/main/java/fittrack/FitTrack.java
  src/main/java/fittrack/messages/Messages.java
  src/main/java/fittrack/parser/Parser.java
  src/main/java/fittrack/ui/Ui.java
  src/test/java/fittrack/UiTest.java
Labels: type.Task, priority.Medium

#106 Add enum class Exercise.
  src/main/java/fittrack/enums/Exercise.java
  src/main/java/fittrack/trainingsession/TrainingSession.java
  src/test/java/fittrack/trainingsession/TrainingSessionTest.java
Labels: type.Enhancement, priority.High

#110 Docs: Write basic Developer Guide for high level functionalities
  docs/DeveloperGuide.md
  docs/HighLevel.png
  docs/HighLevel.puml
  docs/Parser.puml
Labels: type.Task, priority.Low

#112 Add editexercise feature in developer guide.
  docs/DeveloperGuide.md
  docs/TrainingSessionClassDiagram.puml
  docs/TrainingSessionEditState.png
  docs/TrainingSessionEditState.puml
  docs/TrainingSessionInitialState.png
  docs/TrainingSessionInitialState.puml
  docs/editExerciseSequenceDiagram.png
  docs/editExerciseSequenceDiagram.puml
  docs/viewSessionSequenceDiagram.puml
Labels: priority.High

#115 Add user input field to each Exercise enum.
  src/main/java/fittrack/enums/Exercise.java
Labels: type.Task, priority.Medium

#117 Fix: Modify Parser to use new Exercise enum String mapping
  FitTrackLogger.log
  FitTrackLogger.log.lck
  src/main/java/fittrack/parser/Parser.java
  src/test/java/fittrack/ui/UiTest.java
Labels: type.Task, priority.High

#145 Branch minor formatting
  docs/Calculator.puml
  src/main/java/fittrack/calculator/Calculator.java
  src/main/java/fittrack/calculator/PullUpCalculator.java
  src/main/java/fittrack/calculator/ShuttleRunCalculator.java
  src/main/java/fittrack/calculator/SitAndReachCalculator.java
  src/main/java/fittrack/calculator/SitUpCalculator.java
  src/main/java/fittrack/calculator/StandingBroadJumpCalculator.java
  src/main/java/fittrack/calculator/WalkAndRunCalculator.java
  src/main/java/fittrack/exercisestation/PullUpStation.java
  src/main/java/fittrack/exercisestation/ShuttleRunStation.java
  src/main/java/fittrack/exercisestation/SitAndReachStation.java
  src/main/java/fittrack/exercisestation/SitUpStation.java
  src/main/java/fittrack/exercisestation/StandingBroadJumpStation.java
  src/main/java/fittrack/exercisestation/WalkAndRunStation.java
Labels: type.Task, priority.Low

#149 Upload general UG format.
  docs/README.md
Labels: priority.High

#148 add goals features to UG - add, delete, list goals
  docs/UserGuide.md
  src/test/java/fittrack/fitnessgoals/FitnessGoalTest.java
Labels: type.Task, priority.Low

#150 docs: update user guide command summary table for clarity and formatting
  docs/UserGuide.md
Labels: type.Task, priority.Low

#151 146 docs write ug for high level functionalities
  docs/UserGuide.md
Labels: priority.High

#152 Docs: Write UG for High Level Functionalities
  FitTrackLogger.log
  FitTrackLogger.log.lck
  docs/UserGuide.md
  src/main/java/fittrack/messages/Messages.java
Labels: type.Task, priority.Medium

#158 Docs: Update DG High Level Functionalities
  .gitignore
  FitTrackLogger.log
  docs/DeveloperGuide.md
  docs/Diagrams/Archi_Architecture.puml
  docs/Diagrams/Class_AddTrainingSession.puml
  docs/Diagrams/Class_DeleteTrainingSession.puml
  docs/Diagrams/Class_ListTrainingSessions.puml
  docs/Diagrams/Class_Overall.puml
  docs/Diagrams/Class_SetUser.puml
  docs/Diagrams/Class_Storage.puml
  docs/Diagrams/Class_ViewTrainingSession.puml
  docs/HighLevel.png
  docs/Images/Archi_Architecture.png
  docs/Images/Class_AddTrainingSession.png
  docs/Images/Class_DeleteTrainingSession.png
  docs/Images/Class_ListTrainingSessions.png
  docs/Images/Class_Overall.png
  docs/Images/Class_SetUser.png
  docs/Images/Class_Storage.png
  docs/Images/Class_ViewTrainingSession.png
  src/main/java/fittrack/ui/Ui.java
Labels: type.Task, priority.Low

#166 Update DG for Edit Exercise feature.
  docs/DeveloperGuide.md
  docs/Diagrams/Class_TrainingSessionEditState.puml
  docs/Diagrams/Class_TrainingSessionInitialState.puml
  docs/Diagrams/Sequence_editExercise.puml
  docs/Images/Class_TrainingSessionEditState.png
  docs/Images/Class_TrainingSessionInitialState.png
  docs/Images/Sequence_editExercise.png
  docs/TrainingSessionEditState.png
  docs/TrainingSessionEditState.puml
  docs/TrainingSessionInitialState.png
  docs/TrainingSessionInitialState.puml
  docs/editExerciseSequenceDiagram.png
Labels: priority.Low
